### ISSUE TITLE
Administrative units with directional connectivity?

### ISSUE THREAD

**Issue by kfesenmyer** [cbig/zonation-core#12]
Is it possible to use administrative units with directional connectivity in Zonation using the core area zonation algorithm? I receive the following error when I attempt to run a scenario with admin. units with directional connectivity. I do not receive the error and get valid output when I run an identical scenario without the administrative units. 

"Could not read BQP/tree conn profiles file." 

The administrative units load properly.  This is for Zonation 3.1.11. When I attempt to run the scenario without administrative units using the identical code in Zonation 4.0, I am unable to get prop. output. I receive the comment: 

"not writing 'proportional loss map'"

Can you offer any guidance for these 2 issues?

Thank you!

**Comment by PKullberg** [comment]
You should be able to do that at least in Zonation 4.0. I wasn't able to reproduce this error with dummy data on Ubuntu 14.04.4 and Z 4.0. @kfesenmyer could you provide further information on the setup and your system?

Quite common reasons for errors like "Could not read BQP/tree conn profiles file.", are typos in paths or file names, but it is strange if the exactly same set up without ADMUs disabled work. Nevertheless, it could be worth to double check them fist.

**Comment by kfesenmyer** [comment]
Thanks for your reply.  I'm having the issue with ADMUs and connectivity running Zonation 3.1.11 on Windows Server 2008 R2 Enterprise.  

My ADMUs do not respect basin boundaries - meaning drainage networks contain multiple ADMUs - but do respect planning unit boundaries.  I have seen that when I run CAZ with tree connectivity/BQP and use the mask feature to perform a regional analysis, that the tree connectivity will be "reset" to a basin terminus (ocean) where it exits the region.  Does the same correction apply when using ADMUs? 

When I try and check this issue running Zonation 4.0 on Windows 7 Professional with ADMUs, I get the same error as 3.1.11 ("Could not read BQP/tree conn profiles file."). When I run the same setup (CAZ with tree connectivity) but without ADMUs I get successful output - the tree connectivity works -except I am unable to get .prop output.  The same setup produces a .prop output in 3.1.11 and a .rank output that is identical with 4.0 .rank output.  The comments from the 4.0 text file are below. 

"\* Writing final output files...
Writing file of feature information: output/01_PISCES_extant_all_conn_noTrans.features_info.txt
Writing file of performance (representation, coverage, etc.) curves: output/01_PISCES_extant_all_conn_noTrans.curves.txt
Writing output ranking as an image...
Saving image: output/01_PISCES_extant_all_conn_noTrans.png (PNG format)
Writing ranking as a GIS raster map...
Saving raster: output/01_PISCES_extant_all_conn_noTrans.rank.img (HFA format)
 Note: not writing 'proportional loss map'
No automated post-processing file specified"

**Comment by PKullberg** [comment]
Sorry for my slow answer. We are unfortunately currently lacking resources for maintenance and support. 

First, I suggest always using the latest version, Zonation 4, for the analyses. The .prop file isn't anymore a default output in Z4 (unlike Z3), but can be produced by adding following line to the settings file: “output proportional loss ranking = 1”

The only way that I could reproduce your error message was to write a wrong path or file name for “BQP profiles file” in the .dat file. So, I suggest checking that very carefully. 

In addition, when running analyses with ADMUs and NQP I encountered sometime a mysterious seqfault error. It is hard to say what exactly causes this problem as it only happened with some runs but not with others. Nevertheless, if this happens, you could try to rename or delete the old results folder and restarting the GUI (if you are using it). Sometimes it helps.

-Peter

**Comment by PKullberg** [comment]
The seqfault that I mentioned in the previous post was caused by an incorrect directed connectivity tree definition file: Only one downstream connection is allowed per planning unit. One should be extra carefully here since instead of stopping with a clear error message Zonation can run through with errors only reported in the log file or crash with segmentation fault. Also if the name / path to the file is wrong Zonation runs but produces an output without of efects tree connectivity (Error is reported in the output, but it doesn’t stop the run).

I created a simple dummy example for testing runs with NQP and ADMU that can be found here: https://github.com/PKullberg/Z_test_NQP.  If you want to test whether your problem is caused by data / setup files or if it is a specific problem for your system, you can try running it. I have tested it with Ubuntu 14.04 and windows 7 and both worked fine.
