### ISSUE TITLE
Importance of heading [Settings]

### ISSUE THREAD

**Issue by tigcs** [cbig/zonation-core#13]
I have experienced a problem runing Zonation 4.0.0 rc. Due to our mistake we wrote "[Settings]" in lowercase, like this "[settings]". It was not given any warning about it, nor in the manual, nor in the GUI console. Even so Zonation ran, but some of our settings, like "use mask" and "planing units", for example, were ignored.
 I suggest some kind of warning about the importance of right spelling of settings heading.

**Comment by PKullberg** [comment]
Thanks for pointing this out , there is definitely space for improvement here. Currently Zonation is very sensitive for correct spelling of the commands in the in the settings files. The default is that only the lines that area exactly matching to known commands are read and other lines area ignored. This means that if the commands themselves are not correctly written no error messages are outputted (as the lines are omitted) and the same is true for the headings too. I agree with you that there should be at least a warning about possibly misspelled commands. I also think that the headings shouldn’t be obligatory like now when commands from that group are not read if the corresponding heading is not included. 

Unfortunately we are not releasing a new version of the software anytime soon, but the manual could be updated to make this more clear.
