### ISSUE TITLE
Zonation does not produce grp_curves output.

### ISSUE THREAD

**Issue by PaulaRotter** [cbig/zonation-core#25]
Hello,

I am unable to create the `grp_cruves.txt` output file and cannot find out what is wrong with my input data or configuration. Maybe someone can help me to find the problem?

SurETE.bat

```
call zig4 -r SurETE/SurETE.dat SurETE/SurETE.spp SurETE/output/SurETE.txt 0.0 0 1.0 1 --grid-output-formats=asc --image-output-formats=png
```

SurETE.dat

``` 
[settings]
removal rule = 1
use groups = 1
groups file = SurETE/SurETE_groups.txt
warp factor = 1000
edge removal = 0
add edge points = 0
```
Here is my groups file [SurETE_groups.txt](https://github.com/cbig/zonation-core/files/4122549/SurETE_groups.txt), it has the same number and order of entries as the .spp file.

The `.dat`, `.spp` and groups file are all located in the `SurETE/`  subdirectory of where the `.bat` file is located. 

I am using Zonation version `4.0.0rc1_compact` under Windows. Everything else works fine.

Thanks, Paula

**Comment by PKullberg** [comment]
Hi,

Zonation is extremely picky about getting all the inputs exactly as they should be, but unfortunately at the same time not that vocal about if it does not understand something.

In your case, I think that the heading "[settings]" in the .dat file should be "[Settings]" (with capital S). If you look closer to your results you'll probably find that none of the settings were actually read, but instead defaults were used. 

Hopefully this helps!

**Comment by PaulaRotter** [comment]
Hi,

thank you very much for the quick answer! This was the issue and your answer helped a lot!

Paula
