### ISSUE TITLE
Data Input error

### ISSUE THREAD

**Issue by biswasdibyendu** [cbig/zonation-core#27]
Hello!
I am using a raster of the probability of species distribution for the feature file and using only one feature.
But every time it is showing error:

Load failed: Could not load raster file 1.0 E:/WII/Zonation/Test01/SDM07.asc
Data input error. Could not successfully process input files.

What could be the possible reason? 
Please help!

**Comment by jlehtoma** [comment]
It's hard to say exactly as there are multiple possible reasons. At least these come to mind:

1. The file doesn't exist where the path thinks it exists
2. ASCII raster header is malformed. If you've used ArcGIS to produce the raster file this could be the reason. You could try transforming your ASCII raster into e.g. a .tif file.

**Comment by biswasdibyendu** [comment]
Thank you but I think it has some other problem.
1. I have copied the path and used the backslash in order to secure the correct path.
2. I have used both ASCII as well as TIFF but it is showing the same error.

**Comment by biswasdibyendu** [comment]
Well, I suppose I have found the error.  In the 4th column in .spp file, I have used 1.0 instead of 1. 
Therefore, Closing the issue!
Thank you, @jlehtoma
