### ISSUE TITLE
Cost found outside analysis area

### ISSUE THREAD

**Issue by biswasdibyendu** [cbig/zonation-core#28]
While running zonation with CAZ algorithm, I am encountering a **problem (which is showing in GUI console**) saying -  "**Zonation core process 'E:/WII/Zonation/Final/output': something went wrong. See the 'text output' tab in the main window (or output file E:/WII/Zonation/Final/output) for more information. The process finished without being able to remove all the cells (0 out of -1 removed)"**

Though, it has generated output result of cell removal and related cost. The cost layer analysis holds shows the following - 
**Analyzing cost layer...
   Note: cost found outside of analysis area, x: 352, y: 105, status: -1
   Note: cost found outside of analysis area, x: 362, y: 123, status: -1
   Note: cost found outside of analysis area, x: 103, y: 135, status: -1
   Note: cost found outside of analysis area, x: 9, y: 207, status: -1
Total cost in cost layer: 755870, cost inside study/analysis area = 755804, cost outside = 65.6381**

What is the actual problem? Though I have used layers with same extent, projection and resolution.

@jlehtoma

**Comment by jlehtoma** [comment]
My guess would be that even if the extent, projection and resolution are the same, you have cost data in cells (with your extent) that don't have any values in any of the actual feature rasters. But it's hard to tell.

I'm closing this issue as it seems to be more of a usage issue than a bug in the software.
