### ISSUE TITLE
Compiling Zonation on Ubuntu 20.04

### ISSUE THREAD

**Issue by skiptoniam** [cbig/zonation-core#29]
Hi,

I realise that the current build from source version is for Ubuntu 14.04. Has there been any effort to update these for more recent releases? Great software so it would nice to be able to build it on linux.

Cheers,

Skip

**Comment by jlehtoma** [comment]
Unfortunately no, AFAIK there hasn't been an effort to update Zonation v4 to a more recent release. Right now Docker might be your best option, have a look at [this issue](https://github.com/cbig/zonation-core/issues/21) if you haven't already.

**Comment by skiptoniam** [comment]
Hi @jlehtoma, I have used @wkmor1's docker image in the past, but looks like he is not currently supporting the trusty release. I'll email him to suss out what is happening. Thanks for the quick reply.

**Comment by wkmor1** [comment]
Zonation v4 is pegged to qt4 which is end of life and was removed from ubuntu at 20.04. I think it would be possible to get qt4 installed in 20.04 but not sure if that is good idea. Docker is probs your best bet. I last updated my image in 2019 and switched to debian. qt4 is now not in the latest debian either so I have fixed the image to debian:buster. Have added the image to the github container reg so you should be able to pull a buster based image directly from github with 
```
docker pull ghcr.io/wkmor1/zig4
```

**Comment by skiptoniam** [comment]
@wkmor1 sweet! I'll have a look. I hope you are travelling well mate. Thanks.
